require "nvchad.mappings"

-- add yours here

local map = vim.keymap.set

map("n", ";", ":", { desc = "CMD enter command mode" })
map("i", "jk", "<ESC>")
map("n", "<leader>w", "<cmd>w<CR>", { desc = "File save" })
map("n", "<C-h>", "<cmd>nohlsearch<CR>", { desc = "Search clear highlight" })
map("v", "<C-h>", "<cmd>nohlsearch<CR>", { desc = "Search clear highlight" })
map("n", "<leader>,", "<cmd>set invlist<CR>", { desc = "Editor toggle hidden chars" })
map("n", "<leader><leader>", "<C-^>", { desc = "Buffer alternate buffer" })
map("n", "n", "nzz", { desc = "Search next centered", silent = true })
map("n", "N", "Nzz", { desc = "Search previous centered", silent = true })
map("n", "*", "*zz", { desc = "Search word forward centered", silent = true })
map("n", "#", "#zz", { desc = "Search word backward centered", silent = true })

map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<CR>", { desc = "Diagnostics trouble" })
map("n", "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0<CR>", { desc = "Diagnostics buffer trouble" })
map("n", "<leader>xs", "<cmd>Trouble symbols toggle focus=false<CR>", { desc = "Symbols trouble" })
map("n", "<leader>xl", "<cmd>Trouble lsp toggle focus=false win.position=right<CR>", { desc = "LSP trouble" })
map("n", "<leader>xq", "<cmd>Trouble qflist toggle<CR>", { desc = "Quickfix trouble" })

map("n", "<leader>tt", function()
  require("neotest").run.run()
end, { desc = "Test nearest" })
map("n", "<leader>tf", function()
  require("neotest").run.run(vim.fn.expand "%")
end, { desc = "Test file" })
map("n", "<leader>ta", function()
  require("neotest").run.run(vim.uv.cwd())
end, { desc = "Test all" })
map("n", "<leader>ts", function()
  require("neotest").summary.toggle()
end, { desc = "Test summary" })
map("n", "<leader>to", function()
  require("neotest").output.open { enter = true, auto_close = true }
end, { desc = "Test output" })
map("n", "<leader>tO", function()
  require("neotest").output_panel.toggle()
end, { desc = "Test output panel" })
map("n", "<leader>td", function()
  require("neotest").run.run { strategy = "dap" }
end, { desc = "Test debug nearest" })

map("n", "<leader>db", function()
  require("dap").toggle_breakpoint()
end, { desc = "Debug breakpoint" })
map("n", "<leader>dB", function()
  require("dap").set_breakpoint(vim.fn.input "Breakpoint condition: ")
end, { desc = "Debug conditional breakpoint" })
map("n", "<leader>dc", function()
  require("dap").continue()
end, { desc = "Debug continue" })
map("n", "<leader>di", function()
  require("dap").step_into()
end, { desc = "Debug step into" })
map("n", "<leader>do", function()
  require("dap").step_over()
end, { desc = "Debug step over" })
map("n", "<leader>dO", function()
  require("dap").step_out()
end, { desc = "Debug step out" })
map("n", "<leader>dr", function()
  require("dap").repl.toggle()
end, { desc = "Debug repl" })
map("n", "<leader>du", function()
  require("dapui").toggle()
end, { desc = "Debug ui" })
map("n", "<leader>dx", function()
  require("dap").terminate()
end, { desc = "Debug terminate" })

-- map({ "n", "i", "v" }, "<C-s>", "<cmd> w <cr>")
